FORMAT: 1A

# F&O Phoenix API
Universal API for Frank & Oak.

# Group Customers

Customers related resources of the **F&O Phoenix API**


Attributes
- `id` - Customer's ID
- `website_id` - The website id associated to the Customer's account
- `created_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when this object was created
- `updated_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for last time this object was updated - *optional*
- `email` - Customer's Email Address
- `first_name` - Customer's first name
- `last_name` - Customer's last name
- `gender` - Customer's gender (male or female) - *optional*
- `birthdate` - Customer's birthdate - *optional*
- `id_hash` - Customer's encrypted ID hash
- `default_shipping_address_id` - Customer's default shipping address ID - *optional*
- `default_billing_address_id` - Customer's default billing address ID - *optional*
- `store_credit` - Customer's Store Credit (can't be updated from here)
- `facebook_id` - Customer's facebook ID - *optional*
- `google_id` - Customer's google ID - *optional*
- `style` - Customer's style (casual, dressy, etc.) - *optional*
- `shirt_size` - Customer's shirt size (XL, L...) - *optional*
- `pants_size` - Customer's pants_size (30, 32...) - *optional*
- `blazer_size` - Customer's blazer size (40R, 42R...) - *optional*
- `shoe_size` - Customer's shoe size (10, 11...) - *optional*
- `default_currency` - Customer's default Currency (associated to website_id)
- `is_hc_member` - Customer's subscription status for Hunt Club
- `is_first_time_buyer` - Has Customer purchased anything before? Related to Order history


## Customers Collection [/customers]

+ Model (application/json)

            
    + Body

            [
            {
                "id": 1, 
                "website_id": 1, 
                "created_at": "2015-01-07T13:57:00Z", 
                "updated_at": "2015-01-10T09:11:53Z", 
                "id_hash": "32fe!ifew&?", 
                "email": "michael@frankandoak.com", 
                "first_name": "Michael", 
                "last_name": "Eilers Smith", 
                "gender": "male", 
                "birthdate": "03/17/1983", 
                "default_shipping_address_id":325413, 
                "default_billing_address_id": 270186,
                "store_credit": 41.66, 
                "facebook_id": 4324325242, 
                "google_id": 7643322533243, 
                "style":"casual", 
                "shirt_size":"L", 
                "pants_size":"34", 
                "blazer_size":"40R", 
                "shoe_size":"11", 
                "is_first_time_buyer":false,
                "is_hc_member":true
            }, 
            {
                "id": 2, 
                "website_id": 1, 
                "created_at": "2015-01-07T13:57:00Z", 
                "updated_at": "2015-01-10T09:11:53Z", 
                "id_hash": "r!were43e_)", 
                "email": "sean@frankandoak.com", 
                "first_name": "Sean", 
                "last_name": "Connery", 
                "gender": "male", 
                "birthdate": "03/17/1963", 
                "default_shipping_address_id":325413, 
                "default_billing_address_id": 270186,
                "store_credit": 41.66, 
                "facebook_id": 4324325242, 
                "google_id": 7643322533243, 
                "style":"casual", 
                "shirt_size":"L", 
                "pants_size":"34", 
                "blazer_size":"40R", 
                "shoe_size":"11", 
                "is_first_time_buyer":true,
                "is_hc_member":false
            }
            ]


### List all Customers [GET]

+ Request (application/json)

    + Headers
    
            If-Modified-Since: 2015-01-07T13:57:00Z
            X-Session-Token: grg42gtwegsfr    
            
            
+ Response 200

    [Customers Collection][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)


### Create a Customer [POST]

+ Request (application/json)

    Attributes
    - `website_id` - The website id associated to the Customer's account
    - `email` - Customer's Email Address
    - `first_name` - Customer's first name
    - `last_name` - Customer's last name
    - `gender` - Customer's gender (male or female) - *optional*
    - `birthdate` - Customer's birthdate - *optional*
    - `facebook_id` - Customer's facebook ID - *optional*
    - `google_id` - Customer's google ID - *optional*
    - `style` - Customer's style (casual, dressy, etc.) - *optional*
    - `shirt_size` - Customer's shirt size (XL, L...) - *optional*
    - `pants_size` - Customer's pants_size (30, 32...) - *optional*
    - `blazer_size` - Customer's blazer size (40R, 42R...) - *optional*
    - `shoe_size` - Customer's shoe size (10, 11...) - *optional*


    + Headers
    
            X-Session-Token: grg42gtwegsfr   
            
    + Body
    
            {
                "website_id": 1, 
                "email": "michael@frankandoak.com", 
                "first_name": "Michael", 
                "last_name": "Eilers Smith", 
                "gender": "male", 
                "birthdate": "03/17/1983", 
                "facebook_id": 4324325242, 
                "google_id": 7643322533243
            }

+ Response 201 (application/json)

        {
            "id": 1, 
            "website_id": 1, 
            "created_at": "2015-01-07T13:57:00Z", 
            "id_hash": "32fe!ifew&?", 
            "email": "michael@frankandoak.com", 
            "first_name": "Michael", 
            "last_name": "Eilers Smith", 
            "gender": "male", 
            "birthdate": "03/17/1983", 
            "store_credit": 0,00, 
            "facebook_id": 4324325242, 
            "google_id": 7643322533243, 
            "is_first_time_buyer":true,
            "is_hc_member":false
        }
        
+ Response 400 (application/json)

+ Response 500 (application/json)
        
## Customer [/customers/{id}]

+ Model (application/json)

    + Header
    
    + Body
    
            {
                "id":                                       1,  
                "website_id":                               1, 
                "created_at":                               "2015-01-07T13:57:00Z", 
                "updated_at":                               "2015-01-10T09:11:53Z", 
                "id_hash":                                  "32fe!ifew&?", 
                "email":                                    "michael@frankandoak.com", 
                "first_name":                               "Michael", 
                "last_name":                                "Eilers Smith", 
                "gender":                                   "male", 
                "birthdate":                                "03/17/1983", 
                "store_credit":                             41.66, 
                "facebook_id":                              4324325242, 
                "google_id":                                7643322533243, 
                "style":                                    "casual", 
                "shirt_size":                               "L", 
                "pants_size":                               "34", 
                "blazer_size":                              "40R", 
                "shoe_size":                                "11", 
                "is_first_time_buyer":                      true,
                "is_hc_member":                             false
            }
            
            
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

### Retrieve a Customer [GET]
        
+ Request (application/json)

    Attributes
    - `website_id` - The website id associated to the Customer's account
    
    + Header

            If-Modified-Since: 2015-01-07T13:57:00Z
            X-Session-Token: grg42gtwegsfr           
            

+ Response 200

    [Customer][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)

### Update a Customer [PUT]
+ Request (application/json)

    Attributes
    - `website_id` - The website id associated to the Customer's account
    - `email` - Customer's Email Address - *optional*
    - `first_name` - Customer's first name - *optional*
    - `last_name` - Customer's last name - *optional*
    - `gender` - Customer's gender (male or female) - *optional*
    - `birthdate` - Customer's birthdate - *optional*
    - `default_shipping_address_id` - Customer's default shipping address ID - *optional*
    - `default_billing_address_id` - Customer's default billing address ID - *optional*
    - `store_credit` - Customer's Store Credit - *optional, admin permission*
    - `facebook_id` - Customer's facebook ID - *optional*
    - `google_id` - Customer's google ID - *optional*
    - `style` - Customer's style (casual, dressy, etc.) - *optional*
    - `shirt_size` - Customer's shirt size (XL, L...) - *optional*
    - `pants_size` - Customer's pants_size (30, 32...) - *optional*
    - `blazer_size` - Customer's blazer size (40R, 42R...) - *optional*
    - `shoe_size` - Customer's shoe size (10, 11...) - *optional*
    
    + Header

    + Body

            { 
                "website_id": 1, 
                "email": "michael@frankandoak.com", 
                "first_name": "Michael", 
                "last_name": "Eilers Smith", 
                "gender": "male", 
                "birthdate": "03/17/1983", 
                "facebook_id": 4324325242, 
                "google_id": 7643322533243, 
                "style":"casual", 
                "shirt_size":"L", 
                "pants_size":"34", 
                "blazer_size":"40R", 
                "shoe_size":"11"
            }
        
        
+ Response 200

    [Customer][]
    
+ Response 400 (application/json)

+ Response 500 (application/json)



### Remove a Customer [DELETE]
+ Response 204

+ Response 400 (application/json)

+ Response 500 (application/json)


# Group Products

Attributes
- `id` - Product ID
- `website_id` - The website id associated to the product
- `sku` - The sku of the configurable product
- `name` - Full name
- `description` - Description of the product
- `short_description` - Short description of the product
- `new_from_date` - Starting UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) when product is considered as new
- `new_to_date` - Ending UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) when product is considered as new


- `full_images` - Unbounded image (Array of one url)
- `square_images` - Square images (Array of one url)
- `original_price` - Price of the product (without discount)
- `discount_price` - Price of the product (after discount)
- `huntclub_price` - Price of the product (for HC customers)
- `favorites_count` - Count of Favorites
- `is_huntclub_execlusive` - If this product is HC exclusive
- `inventory_status` - In stock status: (aggregated from its children)
     - `0` - out of stock
     - `1` - in stock
     - `2` - low stock
- `label` - Extra label on the product (Editor's Picks)
- `can_add_to_crate` - If this product can be added to Crate or not
- `is_parent` - Is Product a parent product?
- `created_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when this object was created
- `updated_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for last time this object was updated


## Products Collection [/products]

+ Model (application/json)

            
    + Body

            [
                {
                    "id": 1, 
                    "website_id": 1, 
                    "store_id": 1, 
                    "created_at": "2014-12-15T13:57:00Z", 
                    "updated_at": "2014-12-31T09:11:53Z", 
                    "name": "The Forward Issue", 
                    "image_urls": 
                        [
                            "https://...jpg",
                            "https://...jpg",
                            "https://...jpg"
                        ],
                    "starts_at": "2015-01-01T00:00:00Z", 
                    "expires_at": "2015-31-01T00:00:00Z", 
                    "is_featured": true
                }, 
                            {
                    "id": 7, 
                    "website_id": 1, 
                    "store_id": 1, 
                    "created_at": "2015-02-15T13:57:00Z", 
                    "updated_at": "2014-04-31T09:11:53Z", 
                    "name": "Welcome Offer", 
                    "image_urls": 
                        [
                            "https://...jpg",
                            "https://...jpg"
                        ],
                    "expires_at": "2015-03-31T00:00:00Z", 
                    "is_featured": true,
                    "is_new_buyer_exclusive": true, 
                    "hide_name_over_images": true,
                    "show_expiration": true, 
                    "show_expiration_as_countdown": true
                }, 
                
                {
                    "id": 22, 
                    "website_id": 1, 
                    "store_id": 1, 
                    "created_at": "2014-03-15T13:57:00Z", 
                    "updated_at": "2014-04-31T09:11:53Z", 
                    "name": "Pants", 
                    "image_urls": 
                        [
                            "https://...jpg",
                        ],
                    "expires_at": "2015-01-31T00:00:00Z", 
                    "is_new_buyer_exclusive": true, 
                    "subshops": 
                        [
                            {
                                "id": 221, 
                                "website_id": 1, 
                                "store_id": 1, 
                                "created_at": "2014-03-16T13:57:00Z", 
                                "updated_at": "2014-04-31T09:11:53Z", 
                                "name": "Casual Pants", 
                                "image_urls": 
                                    [
                                        "https://...jpg",
                                    ]
                            },
                            {
                                "id": 222, 
                                "website_id": 1, 
                                "store_id": 1, 
                                "created_at": "2014-03-16T13:57:00Z", 
                                "updated_at": "2014-04-31T09:11:53Z", 
                                "name": "Dressy Pants", 
                                "image_urls": 
                                    [
                                        "https://...jpg",
                                    ]
                            }
                        ]
                }
            ]


### List all Products [GET]

+ Request (application/json)

    + Headers
    
            If-Modified-Since: 2015-01-07T13:57:00Z
            X-Session-Token: grg42gtwegsfr    
            
            
+ Response 200

    [Products Collection][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)


### Create a Product [POST]


+ Request (application/json)

    Attributes
    - `website_id` - The website id associated to the Shop
    - `store_id` - The store id associated to the Shop
    - `name` - The name of the shop
    - `image_urls` - A list of image urls of the shop
    - `starts_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the shop starts - *optional*
    - `expires_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the shop expires - *optional*
    - `is_featured` - Is the shop featured (on the front page)? - *optional*
    - `is_hc_exclusive` - Is the shop only visible to HC members? - *optional*
    - `is_new_buyer_exclusive` - Is the shop only visible to members with no order history? - *optional*
    - `is_first_crate_exclusive` - If is_hc_exclusive is true, is the shop only visible to HC members with no crate history? - *optional*
    - `hide_name_over_images` - Should the name of the shop be shown over images? - *optional*
    - `show_expiration` - If expires_at exists, show expiration date - *optional*
    - `show_expiration_as_countdown` - If expires_at exists and show_expiration is true, show time to expiration as a countdown (vs just date) - *optional*
    - `subshop_ids` - Nested shop ids - *optional*


    + Headers
    
            X-Session-Token: grg42gtwegsfr   
            
    + Body
   
            {
                "website_id": 1, 
                "store_id": 1, 
                "name": "New HC Member Shop", 
                "image_urls": 
                    [
                        "https://...jpg"
                    ],
                "starts_at": "2015-01-01T00:00:00Z", 
                "expires_at": "2015-12-31T23:59:59Z", 
                "is_hc_exclusive": true, 
                "is_first_crate_exclusive": true, 
                "subshop_ids": 
                    [
                        311, 
                        312, 
                        313
                    ]
            }

+ Response 201 (application/json)

    + Body

            {
                "id": 310
                "website_id": 1, 
                "store_id": 1, 
                "created_at": "2014-12-15T13:57:00Z", 
                "name": "New HC Member Shop", 
                "image_urls": 
                    [
                        "https://...jpg"
                    ],
                "starts_at": "2015-01-01T00:00:00Z", 
                "expires_at": "2015-12-31T23:59:59Z", 
                "is_hc_exclusive": true, 
                "is_first_crate_exclusive": true, 
                "subshops": 
                    [
                        {
                            "id": 311,
                            "website_id": 1, 
                            "store_id": 1, 
                            "created_at": "2014-12-15T13:57:00Z", 
                            "name": "HC Shirts", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                    "https://...jpg"
                                ]
                        }, 
                        {
                            "id": 312,
                            "website_id": 1, 
                            "store_id": 1, 
                            "created_at": "2014-12-15T13:57:00Z", 
                            "name": "HC Blazers", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                    "https://...jpg"
                                ]
                        }, 
                        {
                            "id": 313,
                            "website_id": 1, 
                            "store_id": 1, 
                            "created_at": "2014-12-15T13:57:00Z", 
                            "name": "HC Pants", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                    "https://...jpg"
                                ]
                        }
                    ]
            }
        
+ Response 400 (application/json)

+ Response 500 (application/json)
        
## Product [/products/{id}]

+ Model (application/json)

    + Header
    
    + Body
    
            {
                "id": 22, 
                "website_id": 1, 
                "store_id": 1, 
                "created_at": "2014-03-15T13:57:00Z", 
                "updated_at": "2014-04-31T09:11:53Z", 
                "name": "Pants", 
                "image_urls": 
                    [
                        "https://...jpg",
                    ],
                "expires_at": "2015-01-31T00:00:00Z", 
                "is_new_buyer_exclusive": true, 
                "subshops": 
                    [
                        {
                            "id": 221, 
                            "website_id": 1, 
                            "store_id": 1, 
                            "created_at": "2014-03-16T13:57:00Z", 
                            "updated_at": "2014-04-31T09:11:53Z", 
                            "name": "Casual Pants", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                ]
                        },
                        {
                            "id": 222, 
                            "website_id": 1, 
                            "store_id": 1, 
                            "created_at": "2014-03-16T13:57:00Z", 
                            "updated_at": "2014-04-31T09:11:53Z", 
                            "name": "Dressy Pants", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                ]
                        }
                    ]
            }
            
            
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

### Retrieve a Product [GET]
        
+ Request (application/json)

    Attributes
    - `website_id` - The website id associated to the shop
    
    + Header

            If-Modified-Since: 2015-01-07T13:57:00Z
            X-Session-Token: grg42gtwegsfr           
            

+ Response 200

    [Product][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)

### Update a Product [PUT]
+ Request (application/json)

    Attributes
    - `website_id` - The website id associated to the Shop
    - `store_id` - The store id associated to the Shop
    - `name` - The name of the shop
    - `image_urls` - A list of image urls of the shop
    - `starts_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the shop starts - *optional*
    - `expires_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the shop expires - *optional*
    - `is_featured` - Is the shop featured (on the front page)? - *optional*
    - `is_hc_exclusive` - Is the shop only visible to HC members? - *optional*
    - `is_new_buyer_exclusive` - Is the shop only visible to members with no order history? - *optional*
    - `is_first_crate_exclusive` - If is_hc_exclusive is true, is the shop only visible to HC members with no crate history? - *optional*
    - `hide_name_over_images` - Should the name of the shop be shown over images? - *optional*
    - `show_expiration` - If expires_at exists, show expiration date - *optional*
    - `show_expiration_as_countdown` - If expires_at exists and show_expiration is true, show time to expiration as a countdown (vs just date) - *optional*
    - `subshop_ids` - Nested shop ids - *optional*
    
    + Header

    + Body

            {
                "website_id": 1, 
                "store_id": 1, 
                "created_at": "2014-03-15T13:57:00Z", 
                "updated_at": "2014-04-31T09:11:53Z", 
                "name": "Pants", 
                "image_urls": 
                    [
                        "https://...jpg",
                    ],
                "expires_at": "2015-01-31T00:00:00Z", 
                "is_new_buyer_exclusive": true, 
                "subshop_ids": 
                    [
                        221, 
                        222
                    ]
            }
        
        
+ Response 200

    [Product][]
    
+ Response 400 (application/json)

+ Response 500 (application/json)



### Remove a Product [DELETE]
+ Response 204

+ Response 400 (application/json)

+ Response 500 (application/json)




# Group Categories

Categories are categories of products that can be nested.

Attributes
- `id` - Category's ID
- `created_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when this object was created
- `updated_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for last time this object was updated - *optional*
- `name` - The name of the category
- `image_urls` - A list of image urls of the category
- `starts_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the category starts - *optional*
- `expires_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the category expires - *optional*
- `is_featured` - Is the category featured (on the front page)? - *optional*
- `is_hc_exclusive` - Is the category only visible to HC members? - *optional*
- `is_new_buyer_exclusive` - Is the category only visible to members with no order history? - *optional*
- `is_first_crate_exclusive` - Is the category only visible to HC members with no crate history? - *optional*
- `hide_name_over_images` - Should the name of the category be shown over images? - *optional*
- `show_expiration` - If expires_at exists, show expiration date - *optional*
- `show_expiration_as_countdown` - If expires_at exists and show_expiration is true, show time to expiration as a countdown (vs just date) - *optional*
- `subcategories` - Nested categories - *optional*


## Categories Collection [/sites/{id}/stores/{id}/categories]

+ Model (application/json)

            
    + Body

            [
                {
                    "id": 1, 
                    "created_at": "2014-12-15T13:57:00Z", 
                    "updated_at": "2014-12-31T09:11:53Z", 
                    "name": "The Forward Issue", 
                    "image_urls": 
                        [
                            "https://...jpg",
                            "https://...jpg",
                            "https://...jpg"
                        ],
                    "starts_at": "2015-01-01T00:00:00Z", 
                    "expires_at": "2015-31-01T00:00:00Z", 
                    "is_featured": true
                }, 
                            {
                    "id": 7, 
                    "website_id": 1, 
                    "store_id": 1, 
                    "created_at": "2015-02-15T13:57:00Z", 
                    "updated_at": "2014-04-31T09:11:53Z", 
                    "name": "Welcome Offer", 
                    "image_urls": 
                        [
                            "https://...jpg",
                            "https://...jpg"
                        ],
                    "expires_at": "2015-03-31T00:00:00Z", 
                    "is_featured": true,
                    "is_new_buyer_exclusive": true, 
                    "hide_name_over_images": true,
                    "show_expiration": true, 
                    "show_expiration_as_countdown": true
                }, 
                
                {
                    "id": 22, 
                    "website_id": 1, 
                    "store_id": 1, 
                    "created_at": "2014-03-15T13:57:00Z", 
                    "updated_at": "2014-04-31T09:11:53Z", 
                    "name": "Pants", 
                    "image_urls": 
                        [
                            "https://...jpg",
                        ],
                    "expires_at": "2015-01-31T00:00:00Z", 
                    "is_new_buyer_exclusive": true, 
                    "subshops": 
                        [
                            {
                                "id": 221, 
                                "website_id": 1, 
                                "store_id": 1, 
                                "created_at": "2014-03-16T13:57:00Z", 
                                "updated_at": "2014-04-31T09:11:53Z", 
                                "name": "Casual Pants", 
                                "image_urls": 
                                    [
                                        "https://...jpg",
                                    ]
                            },
                            {
                                "id": 222, 
                                "website_id": 1, 
                                "store_id": 1, 
                                "created_at": "2014-03-16T13:57:00Z", 
                                "updated_at": "2014-04-31T09:11:53Z", 
                                "name": "Dressy Pants", 
                                "image_urls": 
                                    [
                                        "https://...jpg",
                                    ]
                            }
                        ]
                }
            ]


### List all Categories [GET]

+ Request (application/json)

    + Headers
    
            If-Modified-Since: 2015-01-07T13:57:00Z
            X-Session-Token: grg42gtwegsfr    
            
            
+ Response 200

    [Categories Collection][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)


### Create a Category [POST]


+ Request (application/json)

    Attributes
    - `name` - The name of the category
    - `image_urls` - A list of image urls of the category
    - `starts_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the category starts - *optional*
    - `expires_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the category expires - *optional*
    - `is_featured` - Is the category featured (on the front page)? - *optional*
    - `is_hc_exclusive` - Is the category only visible to HC members? - *optional*
    - `is_new_buyer_exclusive` - Is the category only visible to members with no order history? - *optional*
    - `is_first_crate_exclusive` - If is_hc_exclusive is true, is the shop only visible to HC members with no crate history? - *optional*
    - `hide_name_over_images` - Should the name of the category be shown over images? - *optional*
    - `show_expiration` - If expires_at exists, show expiration date - *optional*
    - `show_expiration_as_countdown` - If expires_at exists and show_expiration is true, show time to expiration as a countdown (vs just date) - *optional*
    - `subcategory_ids` - Nested category ids - *optional*


    + Headers
    
            X-Session-Token: grg42gtwegsfr   
            
    + Body
   
            {
                "name": "New HC Member Shop", 
                "image_urls": 
                    [
                        "https://...jpg"
                    ],
                "starts_at": "2015-01-01T00:00:00Z", 
                "expires_at": "2015-12-31T23:59:59Z", 
                "is_hc_exclusive": true, 
                "is_first_crate_exclusive": true, 
                "subcategory_ids": 
                    [
                        311, 
                        312, 
                        313
                    ]
            }

+ Response 201 (application/json)

    + Body

            {
                "id": 310,
                "created_at": "2014-12-15T13:57:00Z", 
                "name": "New HC Member Shop", 
                "image_urls": 
                    [
                        "https://...jpg"
                    ],
                "starts_at": "2015-01-01T00:00:00Z", 
                "expires_at": "2015-12-31T23:59:59Z", 
                "is_hc_exclusive": true, 
                "is_first_crate_exclusive": true, 
                "subshops": 
                    [
                        {
                            "id": 311,
                            "created_at": "2014-12-15T13:57:00Z", 
                            "name": "HC Shirts", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                    "https://...jpg"
                                ]
                        }, 
                        {
                            "id": 312,
                            "created_at": "2014-12-15T13:57:00Z", 
                            "name": "HC Blazers", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                    "https://...jpg"
                                ]
                        }, 
                        {
                            "id": 313,
                            "created_at": "2014-12-15T13:57:00Z", 
                            "name": "HC Pants", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                    "https://...jpg"
                                ]
                        }
                    ]
            }
        
+ Response 400 (application/json)

+ Response 500 (application/json)
        
## Category [/sites/{id}/stores/{id}/categories/{id}]

+ Model (application/json)

    + Header
    
    + Body
    
            {
                "id": 22, 
                "created_at": "2014-03-15T13:57:00Z", 
                "updated_at": "2014-04-31T09:11:53Z", 
                "name": "Pants", 
                "image_urls": 
                    [
                        "https://...jpg",
                    ],
                "expires_at": "2015-01-31T00:00:00Z", 
                "is_new_buyer_exclusive": true, 
                "subshops": 
                    [
                        {
                            "id": 221, 
                            "created_at": "2014-03-16T13:57:00Z", 
                            "updated_at": "2014-04-31T09:11:53Z", 
                            "name": "Casual Pants", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                ]
                        },
                        {
                            "id": 222, 
                            "created_at": "2014-03-16T13:57:00Z", 
                            "updated_at": "2014-04-31T09:11:53Z", 
                            "name": "Dressy Pants", 
                            "image_urls": 
                                [
                                    "https://...jpg",
                                ]
                        }
                    ]
            }
            
            
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

### Retrieve a Category [GET]
        
+ Request (application/json)
    
    + Header

            If-Modified-Since: 2015-01-07T13:57:00Z
            X-Session-Token: grg42gtwegsfr           
            

+ Response 200

    [Category][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)

### Update a Category [PUT]
+ Request (application/json)

    Attributes
    - `name` - The name of the shop
    - `image_urls` - A list of image urls of the shop
    - `starts_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the shop starts - *optional*
    - `expires_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when the shop expires - *optional*
    - `is_featured` - Is the shop featured (on the front page)? - *optional*
    - `is_hc_exclusive` - Is the shop only visible to HC members? - *optional*
    - `is_new_buyer_exclusive` - Is the shop only visible to members with no order history? - *optional*
    - `is_first_crate_exclusive` - If is_hc_exclusive is true, is the shop only visible to HC members with no crate history? - *optional*
    - `hide_name_over_images` - Should the name of the shop be shown over images? - *optional*
    - `show_expiration` - If expires_at exists, show expiration date - *optional*
    - `show_expiration_as_countdown` - If expires_at exists and show_expiration is true, show time to expiration as a countdown (vs just date) - *optional*
    - `subshop_ids` - Nested shop ids - *optional*
    
    + Header

    + Body

            {
                "website_id": 1, 
                "store_id": 1, 
                "created_at": "2014-03-15T13:57:00Z", 
                "updated_at": "2014-04-31T09:11:53Z", 
                "name": "Pants", 
                "image_urls": 
                    [
                        "https://...jpg",
                    ],
                "expires_at": "2015-01-31T00:00:00Z", 
                "is_new_buyer_exclusive": true, 
                "subshop_ids": 
                    [
                        221, 
                        222
                    ]
            }
        
        
+ Response 200

    [Category][]
    
+ Response 400 (application/json)

+ Response 500 (application/json)



### Remove a Category [DELETE]
+ Response 204

+ Response 400 (application/json)

+ Response 500 (application/json)


