FORMAT: 1A

# F&O Phoenix API
Universal API for Frank & Oak.

# Group Customers

Customers related resources of the **F&O Phoenix API**

Attributes

- `id` - Customer's ID
- `created_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when this object was created
- `updated_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for last time this object was updated
- `website_id` - The website id associated to the Customer's account
- `email` - Customer's Email Address
- `first_name` - Customer's first name
- `last_name` - Customer's last name
- `gender` - Customer's gender (male or female)
- `id_hash` - Customer's encrypted ID hash
- `store_credit` - Customer's Store Credit (can't be updated from here)
- `facebook_id` - Customer's facebook ID
- `google_id` - Customer's google ID
- `style` - Customer's style (casual, preppy, etc.)
- `shirt_size` - Customer's shirt size (XL, L...)
- `pants_size` - Customer's pants_size (30, 32...)
- `blazer_size` - Customer's blazer size (40R, 42R...)
- `shoe_size` - Customer's shoe size (10, 11...)
- `default_currency` - Customer's default Currency (associated to website_id)
- `is_hc_member` - Customer's subscription status for Hunt Club
- `is_first_time_buyer` - Has Customer purchased anything before? Related to Order history


## Customers Collection [/customers]

### List all Customers [GET]
+ Response 200 (application/json)

    + Headers

    + Body

            [
            {
                "id": 1, 
                "website_id": 1, 
                "created_at": "2015-01-07T13:57:00Z", 
                "updated_at": "2015-01-10T09:11:53Z", 
                "id_hash": "32fe!ifew&?", 
                "email": "michael@frankandoak.com", 
                "first_name": "Michael", 
                "last_name": "Eilers Smith", 
                "gender": "male", 
                "birthdate": "03/17/1983", 
                "default_shipping_address_id":325413, 
                "default_billing_address_id": 270186,
                "store_credit": 41.66, 
                "facebook_id": 4324325242, 
                "google_id": 7643322533243, 
                "style":"casual", 
                "shirt_size":"L", 
                "pants_size":"34", 
                "blazer_size":"40R", 
                "shoe_size":"11", 
                "is_first_time_buyer":false,
                "is_hc_member":true
            }, 
            {
                "id": 2, 
                "website_id": 1, 
                "created_at": "2015-01-07T13:57:00Z", 
                "updated_at": "2015-01-10T09:11:53Z", 
                "id_hash": "r!were43e_)", 
                "email": "sean@frankandoak.com", 
                "first_name": "Sean", 
                "last_name": "Connery", 
                "gender": "male", 
                "birthdate": "03/17/1963", 
                "default_shipping_address_id":325413, 
                "default_billing_address_id": 270186,
                "store_credit": 41.66, 
                "facebook_id": 4324325242, 
                "google_id": 7643322533243, 
                "style":"casual", 
                "shirt_size":"L", 
                "pants_size":"34", 
                "blazer_size":"40R", 
                "shoe_size":"11", 
                "is_first_time_buyer":true,
                "is_hc_member":false
            }
            ]

+ Response 400 (application/json)

+ Response 500 (application/json)


### Create a Customer [POST]

+ Request (application/json)

        {
         "website_id": 1, 
         "email": "michael@frankandoak.com", 
         "first_name": "Michael", 
         "last_name": "Eilers Smith", 
         "gender": "male", 
         "birthdate": "03/17/1983", 
         "facebook_id": 4324325242, 
         "google_id": 7643322533243, 
        }

+ Response 201 (application/json)

        {
         "id": 1, 
         "website_id": 1, 
         "created_at": "2015-01-07T13:57:00Z", 
         "id_hash": "32fe!ifew&?", 
         "email": "michael@frankandoak.com", 
         "first_name": "Michael", 
         "last_name": "Eilers Smith", 
         "gender": "male", 
         "birthdate": "03/17/1983", 
         "store_credit": 0,00, 
         "facebook_id": 4324325242, 
         "google_id": 7643322533243, 
         "is_first_time_buyer":true,
         "is_hc_member":false
        }
        
+ Response 400 (application/json)

+ Response 500 (application/json)
        
## Customer [/customers/{id}]

Attributes:

- `id` - Customer's ID
- `created_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for when this object was created
- `updated_at` - UTC timestamp ([ISO 8601](http://www.w3.org/TR/NOTE-datetime)) for last time this object was updated
- `website_id` - The website id associated to the Customer's account
- `email` - Customer's Email Address
- `first_name` - Customer's first name
- `last_name` - Customer's last name
- `gender` - Customer's gender (male or female)
- `id_hash` - Customer's encrypted ID hash
- `store_credit` - Customer's Store Credit (can't be updated from here)
- `facebook_id` - Customer's facebook ID
- `google_id` - Customer's google ID
- `style` - Customer's style (casual, preppy, etc.)
- `shirt_size` - Customer's shirt size (XL, L...)
- `pants_size` - Customer's pants_size (30, 32...)
- `blazer_size` - Customer's blazer size (40R, 42R...)
- `shoe_size` - Customer's shoe size (10, 11...)
- `default_currency` - Customer's default Currency (associated to website_id)
- `is_hc_member` - Customer's subscription status for Hunt Club
- `is_first_time_buyer` - Has Customer purchased anything before? Related to Order history

+ Model (application/json)

            {
                "id":                                       1,  
                "website_id":                               1, 
                "created_at":                               "2015-01-07T13:57:00Z", 
                "updated_at":                               "2015-01-10T09:11:53Z", 
                "id_hash":                                  "32fe!ifew&?", 
                "email":                                    "michael@frankandoak.com", 
                "first_name":                               "Michael", 
                "last_name":                                "Eilers Smith", 
                "gender":                                   "male", 
                "birthdate":                                "03/17/1983", 
                "store_credit":                             41.66, 
                "facebook_id":                              4324325242, 
                "google_id":                                7643322533243, 
                "style":                                    "casual", 
                "shirt_size":                               "L", 
                "pants_size":                               "34", 
                "blazer_size":                              "40R", 
                "shoe_size":                                "11", 
                "is_first_time_buyer":                      true,
                "is_hc_member":                             false
            }
            
            
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

### Retrieve a Customer [GET]

Attributes:

- `website_id` - The website id associated to the Customer's account
        
+ Request (application/json)

    + Header

        If-Modified-Since: 2015-01-07T13:57:00Z
        X-Session-Token: grg42gtwegsfr           
            

+ Response 200 (application/json)

    + Header
    
    + Body
    
        [Customer][]

+ Response 304

+ Response 400 (application/json)

+ Response 500 (application/json)

### Update a Customer [PUT]
+ Request (application/json)

    + Header

    + Body

        { 
        "website_id": 1, 
        "email": "michael@frankandoak.com", 
        "first_name": "Michael", 
        "last_name": "Eilers Smith", 
        "gender": "male", 
        "birthdate": "03/17/1983", 
        "facebook_id": 4324325242, 
        "google_id": 7643322533243, 
        "style":"casual", 
        "shirt_size":"L", 
        "pants_size":"34", 
        "blazer_size":"40R", 
        "shoe_size":"11"
        }
        
        
+ Response 200 (application/json)

+ Response 400 (application/json)

+ Response 500 (application/json)


    {
        "id": 1,  
        "website_id": 1, 
        "created_at": "2015-01-07T13:57:00Z", 
        "updated_at": "2015-01-10T09:11:53Z", 
        "id_hash": "32fe!ifew&?", 
        "email": "michael@frankandoak.com", 
        "first_name": "Michael", 
        "last_name": "Eilers Smith", 
        "gender": "male", 
        "birthdate": "03/17/1983", 
        "store_credit": 41.66, 
        "facebook_id": 4324325242, 
        "google_id": 7643322533243, 
        "style":"casual", 
        "shirt_size":"L", 
        "pants_size":"34", 
        "blazer_size":"40R", 
        "shoe_size":"11", 
        "is_first_time_buyer":true,
        "is_hc_member":false
    }



### Remove a Customer [DELETE]
+ Response 204

+ Response 400 (application/json)

+ Response 500 (application/json)
